import { observabilityScript } from './observability-page.ts'
/** Self-contained governed portal; text dictionaries own all product copy. */
export const platformPage = '<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/platform/style.css"><title>Agent Platform</title><script src="/platform/app.js" defer></script></head><body><main id="app"></main><div id="notice" role="status" aria-live="polite"></div></body></html>'

/** Portal styles use local semantic tokens and responsive native controls. */
export const platformStyle = ':root{color-scheme:light;--bg:#f4f5f7;--panel:#fff;--text:#182331;--muted:#596579;--line:#d9dfe7;--accent:#2159bd;--danger:#a32d32;font:15px/1.5 system-ui,sans-serif;background:var(--bg);color:var(--text)}*{box-sizing:border-box}body{margin:0}main{max-width:1180px;margin:auto;padding:32px 24px}header{display:flex;align-items:center;gap:16px;flex-wrap:wrap;margin-bottom:24px}h1{font-size:25px;margin:0;margin-right:auto}h2{font-size:20px}h3{font-size:16px;margin:0 0 8px}.muted{color:var(--muted)}nav,.actions{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.card{background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:20px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(270px,1fr));gap:16px}.grid>.card{margin:0}button,input,textarea,select{font:inherit;border:1px solid var(--line);border-radius:6px;padding:9px 12px;background:var(--panel);color:var(--text)}button{cursor:pointer}button:hover{border-color:var(--accent);color:var(--accent)}button.primary{background:var(--accent);color:white;border-color:var(--accent)}button:disabled{opacity:.5;cursor:wait}input,textarea{width:100%}textarea{min-height:140px;resize:vertical}label{display:block;margin:14px 0 6px}label>input[type=checkbox]{width:auto;margin-right:8px}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.6 system-ui,sans-serif}form{max-width:760px}.login{max-width:440px;margin:12vh auto}.analysis-table{overflow-x:auto;margin:12px 0 24px}.analysis-table th{white-space:nowrap}.analysis-table td{min-width:100px}.analysis-table button{white-space:nowrap}table{width:100%;border-collapse:collapse}td,th{padding:10px;text-align:left;border-bottom:1px solid var(--line)}#notice{position:fixed;bottom:20px;right:20px;max-width:80vw;background:var(--text);color:var(--panel);border-radius:8px;padding:12px 18px}#notice:empty{display:none}.badge{font-size:12px;border:1px solid var(--line);border-radius:20px;padding:3px 9px}.row{display:flex;gap:12px;align-items:center;flex-wrap:wrap}a{color:var(--accent)}:focus-visible{outline:3px solid var(--accent);outline-offset:2px}@media(max-width:600px){main{padding:20px 14px}.card{padding:15px}}'

/** Browser code uses textContent for all resource and model values. */
export const platformScript = String.raw`
(() => {
const words = {
 zh: {title:'Agent Platform',subtitle:'团队工作区',login:'登录工作区',credential:'个人访问凭证',loginHelp:'使用管理员为你分配的个人凭证。',logout:'退出',agents:'Agents',resources:'共享资源',members:'成员与治理',create:'创建 Agent',edit:'编辑',name:'名称',description:'说明',prompt:'指令',model:'模型',tools:'工具',skills:'技能',save:'保存',cancel:'取消',back:'返回',versions:'版本与部署',saveVersion:'保存新版本',note:'版本说明',deploy:'部署',rollback:'回滚',run:'运行',runs:'运行记录',input:'任务输入',start:'开始运行',refresh:'刷新',empty:'暂无内容',status:'状态',result:'最终结果',trace:'执行详情',archive:'归档',restore:'恢复',admin:'管理员',developer:'开发者',user:'普通用户',seed:'导入已安装资源',newResource:'注册资源',kind:'类型',tool:'工具',skill:'技能',provider:'模型服务',operation:'工具操作',content:'技能指令',publish:'发布版本',active:'可用',deprecated:'弃用',disabled:'停用',archived:'已归档',resourceUsage:'使用关系',userId:'用户 ID',role:'角色',add:'添加成员',remove:'移除',workspaceName:'工作区名称',audit:'治理记录',saved:'已保存',error:'操作失败，请刷新后重试',noWorkspace:'你尚未加入工作区，请联系管理员。',more:'下一页',owner:'创建者',cancelRun:'取消运行',revision:'修订',version:'版本',deployed:'当前部署',noModel:'请先由管理员注册并发布模型资源。',select:'请选择',language:'English',resolve:'确认外部执行结果',callId:'工具调用 ID',evidence:'核验依据',completed:'已完成',notExecuted:'确认未执行',decision:'核验结果',confirm:'确认',readOnly:'工作区已归档，仅可查看历史',resourceVersion:'发布版本',all:'全部',archivedAgents:'查看已归档 Agent'},
 en: {title:'Agent Platform',subtitle:'Team workspace',login:'Sign in',credential:'Personal access credential',loginHelp:'Use the individual credential provided by your administrator.',logout:'Sign out',agents:'Agents',resources:'Resources',members:'Members & governance',create:'Create Agent',edit:'Edit',name:'Name',description:'Description',prompt:'Instructions',model:'Model',tools:'Tools',skills:'Skills',save:'Save',cancel:'Cancel',back:'Back',versions:'Versions & deployment',saveVersion:'Save new version',note:'Version note',deploy:'Deploy',rollback:'Roll back',run:'Run',runs:'Run history',input:'Task input',start:'Start run',refresh:'Refresh',empty:'No items',status:'Status',result:'Final result',trace:'Execution details',archive:'Archive',restore:'Restore',admin:'Administrator',developer:'Developer',user:'User',seed:'Import installed resources',newResource:'Register resource',kind:'Kind',tool:'Tool',skill:'Skill',provider:'Model provider',operation:'Tool operation',content:'Skill instructions',publish:'Publish version',active:'Active',deprecated:'Deprecated',disabled:'Disabled',archived:'Archived',resourceUsage:'Usage',userId:'User ID',role:'Role',add:'Add member',remove:'Remove',workspaceName:'Workspace name',audit:'Governance history',saved:'Saved',error:'Operation failed. Refresh and retry.',noWorkspace:'You have not joined a workspace. Contact an administrator.',more:'Next page',owner:'Created by',cancelRun:'Cancel run',revision:'Revision',version:'Version',deployed:'Current deployment',noModel:'Ask an administrator to register and publish a model resource first.',select:'Select',language:'中文',resolve:'Confirm external execution outcome',callId:'Tool call ID',evidence:'Verification evidence',completed:'Completed',notExecuted:'Verified not executed',decision:'Verified outcome',confirm:'Confirm',readOnly:'Workspace is archived. History is read-only.',resourceVersion:'Published version',all:'All',archivedAgents:'View archived Agents'}
};
let lang=localStorage.getItem('platform-language') || 'zh';
let me, workspace, section='agents', epoch=0, controller=new AbortController();
const app=document.getElementById('app');
const t=k=>(words[lang] || words.zh)[k] || k;
const el=(tag,text,cls)=>{const node=document.createElement(tag); if(text!==undefined)node.textContent=String(text);if(cls)node.className=cls;return node};
const notice=value=>{document.getElementById('notice').textContent=value;};
const guard=fn=>async()=>{try{notice('');await fn();}catch(error){if(error.name!=='AbortError')notice(error.message || t('error'));}};
function button(label,fn,primary=false){const b=el('button',label,primary?'primary':'');b.type='button';b.onclick=guard(async()=>{b.disabled=true;try{await fn();}finally{b.disabled=false;}});return b;}
function field(form,label,value='',type='text'){const input=type==='textarea'?el('textarea'):el('input');input.type=type;input.value=value;const wrap=el('label',label);wrap.append(input);form.append(wrap);return input;}
function select(form,label,items,value){const input=el('select');for(const [key,title] of items){const option=el('option',title);option.value=key;input.append(option);}if(value!==undefined)input.value=value;const wrap=el('label',label);wrap.append(input);form.append(wrap);return input;}
async function post(path,data){const captured=epoch;const res=await fetch('/platform/'+path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data),signal:controller.signal});const value=await res.json();if(captured!==epoch)throw new DOMException('Stale response','AbortError');if(res.status===401){me=undefined;login();}if(!res.ok)throw new Error(value.error || t('error'));return value;}
const mutationTokens=new Map();
const tokenPositions={createAgent:1,saveVersion:2,deploy:3,createResource:1,publishResource:2,start:2,resolve:5};
async function rpc(operation,...args){const at=tokenPositions[operation];let key;if(at!==undefined){const identity=args.map((value,i)=>i===at?null:value);key=JSON.stringify([workspace?.id,operation,identity]);if(!mutationTokens.has(key))mutationTokens.set(key,args[at]);args[at]=mutationTokens.get(key);}const result=await post('api',{workspaceId:workspace?.id || '',operation,args});if(key)mutationTokens.delete(key);return result;}

function reset(){epoch++;controller.abort();controller=new AbortController();notice('');}
function shell(){app.replaceChildren();const header=el('header');header.append(el('h1',t('title')));if(me){const picker=select(header,t('subtitle'),me.workspaces.map(w=>[w.id,w.name+' · '+t(w.role)]),workspace?.id);picker.onchange=guard(async()=>{reset();workspace=me.workspaces.find(w=>w.id===picker.value);section='agents';await show();});header.append(el('span',me.user.displayName,'muted'),button(t('logout'),async()=>{await post('logout',{});reset();me=undefined;login();}));}header.append(button(t('language'),async()=>{lang=lang==='zh'?'en':'zh';localStorage.setItem('platform-language',lang);if(me)await show();else login();}));app.append(header);if(!me)return;const nav=el('nav');nav.append(button(t('agents'),()=>{section='agents';return show();}));if(workspace?.role!=='user')nav.append(button(t('resources'),()=>{section='resources';return show();}));if(workspace?.role==='admin')nav.append(button(t('workspaceAnalytics'),()=>analytics()));if(workspace?.role==='admin')nav.append(button(t('members'),()=>{section='members';return show();}));app.append(nav);if(workspace?.status==='archived')app.append(el('p',t('readOnly'),'muted'));}
function login(){shell();const form=el('form',undefined,'card login');form.append(el('h2',t('login')),el('p',t('loginHelp'),'muted'));const credential=field(form,t('credential'),'','password');credential.autocomplete='off';credential.required=true;const submit=el('button',t('login'),'primary');submit.type='submit';form.append(submit);form.onsubmit=event=>{event.preventDefault();guard(async()=>{submit.disabled=true;try{await post('login',{token:credential.value});credential.value='';await boot();}finally{submit.disabled=false;}})();};app.append(form);}
async function boot(){me=await rpc('me');workspace=me.workspaces.find(w=>w.id===workspace?.id)||me.workspaces[0];await show();}
async function show(){reset();shell();if(!workspace){app.append(el('p',t('noWorkspace')));return;}if(section==='resources')return resources();if(section==='members')return members();return agents();}
async function agents(cursor,archived=false){const page=await rpc('agents',{limit:24,...(cursor?{cursor}:{}),lifecycle:archived?'archived':'active'});const actions=el('div',undefined,'actions');if(workspace.role!=='user'){if(workspace.status==='active')actions.append(button(t('create'),()=>editor()));actions.append(button(t('archivedAgents'),()=>{shell();return agents(undefined,true);}));}app.append(actions);const grid=el('div',undefined,'grid');for(const a of page.items){const card=el('article',undefined,'card');card.append(el('h3',a.name),el('p',a.description,'muted'));const row=el('div',undefined,'actions');if(a.lifecycle==='active'&&workspace.status==='active')row.append(button(t('run'),()=>composer(a),true));row.append(button(t('runs'),()=>runs(a)));if(workspace.role!=='user'){row.append(button(t('analytics'),()=>analytics(a)),button(t('edit'),()=>editor(a.id)),button(t('versions'),()=>versions(a)));if(workspace.status==='active')row.append(button(t(a.lifecycle==='archived'?'restore':'archive'),async()=>{const full=await rpc('agent',a.id);await rpc('archiveAgent',a.id,full.revision,a.lifecycle!=='archived');await show();}));}card.append(row);grid.append(card);}if(!page.items.length)grid.append(el('p',t('empty')));app.append(grid);if(page.nextCursor)app.append(button(t('more'),()=>{shell();return agents(page.nextCursor,archived);}));}
async function editor(id){const [catalog,a]=await Promise.all([rpc('catalog'),id?rpc('agent',id):Promise.resolve(undefined)]);shell();const form=el('form',undefined,'card');form.append(el('h2',a?t('edit'):t('create')));const name=field(form,t('name'),a?.name||'');const description=field(form,t('description'),a?.description||'');const prompt=field(form,t('prompt'),a?.prompt||'','textarea');const available=catalog.resources.filter(r=>r.status==='active'||r.status==='deprecated');const entries=kind=>available.filter(r=>r.spec.kind===kind).flatMap(r=>r.versions.map(v=>({ref:{resourceId:r.id,versionId:v.id},label:r.name+' · v'+v.versionNumber})));const models=entries('model');if(!models.length){form.append(el('p',t('noModel')));app.append(form);return;}const model=select(form,t('model'),models.map((r,i)=>[String(i),r.label]),String(Math.max(0,models.findIndex(r=>r.ref.versionId===a?.resources?.model.versionId))));const choices={};for(const kind of ['tool','skill']){form.append(el('h3',t(kind==='tool'?'tools':'skills')));choices[kind]=entries(kind).map(row=>{const label=el('label',row.label);const check=el('input');check.type='checkbox';check.checked=(a?.resources?.[kind==='tool'?'tools':'skills']||[]).some(ref=>ref.versionId===row.ref.versionId);label.prepend(check);form.append(label);return {...row,check};});}const save=button(t('save'),async()=>{const refs={model:models[Number(model.value)].ref,tools:choices.tool.filter(r=>r.check.checked).map(r=>r.ref),skills:choices.skill.filter(r=>r.check.checked).map(r=>r.ref)};const selected=catalog.resources.find(r=>r.id===refs.model.resourceId).versions.find(v=>v.id===refs.model.versionId).spec;const input={name:name.value,description:description.value,prompt:prompt.value,model:{provider:selected.provider,model:selected.model},toolIds:[],resources:refs,ownerTeamId:workspace.id,harnessId:'deepseek-harness',tags:a?.tags||[]};if(a)await rpc('updateAgent',a.id,a.revision,input);else await rpc('createAgent',input,crypto.randomUUID());await show();notice(t('saved'));},true);if(workspace.status==='active')form.append(save);form.append(button(t('back'),show));app.append(form);}
async function versions(a,cursor=0){const [page,deployment,full]=await Promise.all([rpc('versions',a.id,cursor),rpc('deployment',a.id),rpc('agent',a.id)]);shell();app.append(el('h2',a.name+' · '+t('versions')));if(workspace.status==='active'&&full.lifecycle==='active'){const form=el('div',undefined,'card');const note=field(form,t('note'));form.append(button(t('saveVersion'),async()=>{await rpc('saveVersion',a.id,full.revision,crypto.randomUUID(),note.value);await versions(a);},true));app.append(form);}for(const v of page.items){const card=el('div',undefined,'card');card.append(el('h3','v'+v.versionNumber+(deployment?.versionId===v.id?' · '+t('deployed'):'')),el('p',v.changeNote),el('span',v.createdBy,'muted'));if(workspace.status==='active'&&full.lifecycle==='active')card.append(button(t('deploy'),async()=>{await rpc('deploy',a.id,v.id,deployment?.revision||0,crypto.randomUUID(),'deploy');await versions(a);}),button(t('rollback'),async()=>{await rpc('deploy',a.id,v.id,deployment?.revision||0,crypto.randomUUID(),'rollback');await versions(a);}));app.append(card);}if(page.nextCursor!==null)app.append(button(t('more'),()=>versions(a,page.nextCursor)));}
function composer(a){shell();const form=el('form',undefined,'card');form.append(el('h2',a.name));const input=field(form,t('input'),'','textarea');form.append(button(t('start'),async()=>{const r=await rpc('start',a.id,input.value,crypto.randomUUID());await runDetail(a,r.id);},true));app.append(form);}
async function runs(a,cursor=0){const page=await rpc('runs',a.id,cursor);shell();app.append(el('h2',a.name+' · '+t('runs')),button(t('refresh'),()=>runs(a,cursor)));for(const r of page.items){const card=el('div',undefined,'card');card.append(el('p',r.createdAt+' · '+r.status),el('p',r.input?.prompt||''),button(t('result'),()=>runDetail(a,r.id)));app.append(card);}if(!page.items.length)app.append(el('p',t('empty')));if(page.nextCursor!==null)app.append(button(t('more'),()=>runs(a,page.nextCursor)));}
async function runDetail(a,id){const r=await rpc('run',a.id,id);shell();const card=el('section',undefined,'card');card.append(el('h2',a.name),el('span',r.status,'badge'),el('h3',t('input')),el('pre',r.input?.prompt||''),el('h3',t('result')),el('pre',r.result?.textPreview||r.error?.message||''));card.append(button(t('refresh'),()=>runDetail(a,id)));if(!['SUCCEEDED','FAILED','CANCELLED'].includes(r.status))card.append(button(t('cancelRun'),async()=>{await rpc('cancel',a.id,id);await runDetail(a,id);}));if(workspace.role!=='user')card.append(button(t('trace'),async()=>{const trace=await rpc('trace',a.id,id);const events=await rpc('traceEvents',a.id,id);const pre=el('pre',JSON.stringify({trace,events},null,2));card.append(pre);}));if(workspace.role==='admin'&&r.status==='BLOCKED'){const form=el('div');form.append(el('h3',t('resolve')));const call=field(form,t('callId'));const decision=select(form,t('decision'),[['completed',t('completed')],['not-executed',t('notExecuted')]]);const evidence=field(form,t('evidence'),'','textarea');form.append(button(t('confirm'),async()=>{await rpc('resolve',a.id,id,call.value,decision.value,evidence.value,crypto.randomUUID());await runDetail(a,id);}));card.append(form);}app.append(card);}
async function resources(){const rows=await rpc('resources');const actions=el('div',undefined,'actions');if(workspace.role==='admin'&&workspace.status==='active')actions.append(button(t('seed'),async()=>{await rpc('seedResources');await show();}),button(t('newResource'),()=>resourceEditor()));app.append(actions);for(const r of rows){const card=el('div',undefined,'card');card.append(el('h3',r.name),el('p',r.description),el('span',t(r.spec.kind)+' · '+t(r.status)+' · '+t('resourceVersion')+': '+r.versions.length,'muted'));const row=el('div',undefined,'actions');if(workspace.role==='admin'&&workspace.status==='active'){row.append(button(t('edit'),()=>resourceEditor(r)),button(t('publish'),async()=>{await rpc('publishResource',r.id,r.revision,crypto.randomUUID());await show();}));const state=select(row,t('status'),['active','deprecated','disabled','archived'].map(s=>[s,t(s)]),r.status);row.append(button(t('save'),async()=>{await rpc('resourceStatus',r.id,r.revision,state.value);await show();}));}row.append(button(t('resourceUsage'),async()=>{const uses=await rpc('resourceUsage',r.id);card.append(el('pre',uses.map(u=>u.agentName+' · '+(u.versionNumber||'')).join('\n')||t('empty')));}));card.append(row);app.append(card);}if(!rows.length)app.append(el('p',t('empty')));}
function resourceEditor(resource){shell();const form=el('form',undefined,'card');const name=field(form,t('name'),resource?.name||'');const description=field(form,t('description'),resource?.description||'');const kind=select(form,t('kind'),['model','tool','skill'].map(k=>[k,t(k)]),resource?.spec.kind||'tool');if(resource)kind.disabled=true;const config=el('div');form.append(config);let fields={};function showConfig(){config.replaceChildren();fields={};if(kind.value==='model'){fields.provider=field(config,t('provider'),resource?.spec.provider||'');fields.model=field(config,t('model'),resource?.spec.model||'');}else if(kind.value==='tool'){fields.operation=field(config,t('operation'),resource?.spec.operation||'');}else fields.content=field(config,t('content'),resource?.spec.content||'','textarea');}kind.onchange=showConfig;showConfig();form.append(button(t('save'),async()=>{const spec={kind:kind.value};for(const [key,input] of Object.entries(fields))spec[key]=input.value;const input={name:name.value,description:description.value,ownerTeamId:workspace.id,spec};if(resource)await rpc('updateResource',resource.id,resource.revision,input);else await rpc('createResource',input,crypto.randomUUID());await show();},true),button(t('back'),show));app.append(form);}
async function members(){const rows=await rpc('members');const form=el('div',undefined,'card');const user=field(form,t('userId'));const role=select(form,t('role'),['user','developer','admin'].map(r=>[r,t(r)]));form.append(button(t('add'),async()=>{await rpc('member',user.value,role.value,0);await boot();}));app.append(form);for(const member of rows){const card=el('div',undefined,'card row');card.append(el('strong',member.displayName),el('span',member.userId,'muted'));const role=select(card,t('role'),['user','developer','admin'].map(r=>[r,t(r)]),member.role);card.append(button(t('save'),async()=>{await rpc('member',member.userId,role.value,member.revision);await boot();}),button(t('remove'),async()=>{await rpc('member',member.userId,null,member.revision);await boot();}));app.append(card);}const settings=el('div',undefined,'card');const name=field(settings,t('workspaceName'),workspace.name);const state=select(settings,t('status'),['active','archived'].map(s=>[s,t(s)]),workspace.status);settings.append(button(t('save'),async()=>{await rpc('workspace',workspace.revision,name.value,state.value);await boot();}),button(t('audit'),async()=>{const rows=await rpc('audit');settings.append(el('pre',rows.map(r=>r.occurredAt+' · '+r.actorId+' · '+r.action+' · '+r.targetId).join('\n')||t('empty')));}));app.append(settings);}
${observabilityScript}
guard(boot)();
})();`
